user nginx;
worker_processes auto;
events { worker_connections 1024; }
http {
  upstream django_backend { server web:8000; }
  upstream react_frontend { server frontend:3000; }
  server {
    listen 80;
    location /api/ { proxy_pass http://django_backend; }
    location / { proxy_pass http://react_frontend; }
  }
}
