# Generated by Django 4.2 on 2026-04-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0004_patient_password_reset_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalObservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("bp_systolic", models.PositiveIntegerField()),
                ("bp_diastolic", models.PositiveIntegerField()),
                ("heart_rate", models.PositiveIntegerField()),
                ("temperature", models.DecimalField(decimal_places=1, max_digits=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vitals", to="patients.patient"),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="recorded_vitals", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
