# Generated by Django 6.0.3 on 2026-04-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='hash',
            field=models.CharField(default='legacy', editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
